#pragma once

enum SystemState : uint8_t
{
  SYS_INIT = 0,
  SYS_IDLE,
  SYS_RUN,
  SYS_ERROR
};

enum ControlState : uint8_t
{
  CONTROL_START_SAMPLING = 0,
  CONTROL_WAIT_SAMPLING,
  CONTROL_CALCULATE_CONTROL_LAWS,
  CONTROL_FINISHED_CONTROL_LAWS,
  CONTROL_UPDATE_PWM_DUTY_CYCLES,
  CONTROL_FINISHED_CYCLE
};
